version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running Robot Framework tests...
      - robot api_test.robot
      - echo "Sleeping for 10 seconds to wait for output.xml"
      - sleep 10  # Add a delay to ensure output.xml is fully generated
      - python emailReport.py
artifacts:
  files:
    - output.xml
    - report.html
